lib/pejs/web/router.ex
defmodule Pejs.Web.Router do
  use Pejs.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Pejs.Web do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", Pejs.Web do
  #   pipe_through :api
  # end
end

lib/spejs_web/router.ex
defmodule SpejsWeb.Router do
  use SpejsWeb, :router
  use Plug.ErrorHandler
  use Sentry.Plug
  use Coherence.Router         # Add this

  pipeline :browser do
    plug :accepts, ~w(html)
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session  # Add this
    plug :put_user_token
  end

  pipeline :protected do
    plug :accepts, ~w(html)
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session, protected: true  # Add this
    plug :put_user_token
  end

  pipeline :api do
    plug Corsica, origins: "*", allow_headers: ["accept", "content-type"]
    plug :accepts, ["json"]
  end

  # Add this block
  scope "/" do
    pipe_through :browser
    coherence_routes()
  end

  # Add this block
  scope "/" do
    pipe_through :protected
    coherence_routes :protected
  end

  scope "/", SpejsWeb do
    pipe_through :browser

    get "/", PageController, :index
    # add public resources below
  end

  scope "/", SpejsWeb do
    pipe_through :protected

    # add protected resources below
    resources "/users", UserController
    resources "/devices", DeviceController
    resources "/networks", NetworkController
  end

  # Other scopes may use custom stacks.
  scope "/api", SpejsWeb do
    pipe_through :api
    get "/", InteractionsController, :index
    post "/interactions/devices", InteractionsController, :devices
    post "/interactions/clear_devices", InteractionsController, :clear_devices
    get "/at_hackerspace", InteractionsController, :at_hackerspace

    post "/sensors/update", Api.SensorsController, :update
    get "/sensors/sensor/:sensor_id", Api.SensorsController, :find_sensor
    get "/sensors", Api.SensorsController, :all_sensors
  end

  defp put_user_token(conn, _) do
    case current_user = Coherence.current_user(conn) do
      nil -> conn
      _ ->
        user_token = Phoenix.Token.sign(conn, "user_token", current_user.email)
        conn |> assign(:user_token, user_token)
    end
  end
end

lib/spejs/accounts/device.ex
defmodule Spejs.Accounts.Device do
  use SpejsWeb, :model

  schema "accounts_devices" do
    field :name, :string
    field :mac, :string
    field :ip, :string
    field :flag, :integer

    belongs_to :user, Spejs.Accounts.User
    belongs_to :network, Spejs.Accounts.Network

    timestamps()
  end
end

lib/spejs_web/controllers/device_controller.ex
defmodule SpejsWeb.DeviceController do
  use SpejsWeb, :controller

  alias Spejs.Accounts

  def index(conn, _params) do
    devices = Accounts.list_devices()
      |> Accounts.preload(:user)
      |> Accounts.preload(:network)
    render(conn, "index.html", devices: devices)
  end

  def new(conn, _params) do
    changeset = Accounts.change_device(%Spejs.Accounts.Device{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"device" => device_params}) do
    case Accounts.create_device(device_params) do
      {:ok, device} ->
        conn
        |> put_flash(:info, "Device created successfully.")
        |> redirect(to: device_path(conn, :show, device))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    device = Accounts.get_device!(id)
      |> Accounts.preload(:network)
    render(conn, "show.html", device: device)
  end

  def edit(conn, %{"id" => id}) do
    device = Accounts.get_device!(id)
      |> Accounts.preload(:network)
    changeset = Accounts.change_device(device)
    render(conn, "edit.html", device: device, changeset: changeset)
  end

  def update(conn, %{"id" => id, "device" => device_params}) do
    device = Accounts.get_device!(id)

    case Accounts.update_device(device, device_params) do
      {:ok, device} ->
        conn
        |> put_flash(:info, "Device updated successfully.")
        |> redirect(to: device_path(conn, :show, device))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", device: device, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    device = Accounts.get_device!(id)
    {:ok, _device} = Accounts.delete_device(device)

    conn
    |> put_flash(:info, "Device deleted successfully.")
    |> redirect(to: device_path(conn, :index))
  end
end

lib/spejs_web/views/device_view.ex
defmodule SpejsWeb.DeviceView do
  use SpejsWeb, :view

  def available_users do
    Spejs.Accounts.list_users
      |> Enum.map(&{&1.name, &1.id})
  end

  def available_networks do
    Spejs.Accounts.list_networks
      |> Enum.map(&{&1.name, &1.id})
  end

end

lib/spejs_web/templates/device/edit.html.eex
<h2>Edit Device</h2>

<%= render "form.html", changeset: @changeset,
                        action: device_path(@conn, :update, @device) %>

<span><%= link "Back", to: device_path(@conn, :index), class: "btn btn-default" %></span>

lib/spejs_web/templates/device/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, :user_id, class: "control-label" %>
    <%= select f, :user_id, available_users(), class: "form-control", prompt: "Choose device owner" %>
    <%= error_tag f, :user_id %>
  </div>

  <div class="form-group">
    <%= label f, :network_id, class: "control-label" %>
    <%= select f, :network_id, available_networks(), class: "form-control", prompt: "Choose network" %>
    <%= error_tag f, :network_id %>
  </div>

  <div class="form-group">
    <%= label f, :ip, class: "control-label" %>
    <%= text_input f, :ip, class: "form-control", readonly: :readonly, disabled: :disabled %>
    <%= error_tag f, :ip %>
  </div>

  <div class="form-group">
    <%= label f, :mac, class: "control-label" %>
    <%= text_input f, :mac, class: "form-control", readonly: :readonly, disabled: :disabled %>
    <%= error_tag f, :mac %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/spejs_web/templates/device/index.html.eex
<div class="pull-right">
  <%= link "New Device", to: device_path(@conn, :new), class: "btn btn-primary" %>
  <%= button "Clear devices", to: interactions_path(@conn, :clear_devices), class: "btn btn-default" %>
</div>

<h2>Listing Devices</h2>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Identifier</th>
      <th>IP</th>
      <th>Network</th>
      <th>Active</th>
      <th>User</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for device <- @devices do %>
    <tr id="<%= device.name %>">
      <td class="name"><%= device.name || "" %></td>
      <td class="mac"><%= device.mac || "" %></td>
      <td class="ip"><%= device.ip || "" %></td>
      <td class="network"><%= if device.network do device.network.name end%></td>
      <td class="flag"><%= device.flag || ""%></td>
      <td class="owner"><%= if device.user do device.user.name end%></td>

      <td class="text-right">
        <span><%= link "Show", to: device_path(@conn, :show, device), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Edit", to: device_path(@conn, :edit, device), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Delete", to: device_path(@conn, :delete, device), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New Device", to: device_path(@conn, :new), class: "btn btn-primary pull-right" %>

lib/spejs_web/templates/device/new.html.eex
<h2>New Device</h2>

<%= render "form.html", changeset: @changeset,
                        action: device_path(@conn, :create) %>

<span><%= link "Back", to: device_path(@conn, :index), class: "btn btn-default" %></span>

lib/spejs_web/templates/device/show.html.eex
<h2>Show Device</h2>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @device.name %>
  </li>

  <li>
    <strong>Mac:</strong>
    <%= @device.mac %>
  </li>

  <li>
    <strong>Flag:</strong>
    <%= @device.flag %>
  </li>

  <li>
    <strong>IP:</strong>
    <%= @device.ip %>
  </li>

  <li>
    <strong>Network:</strong>
    <%= if @device.network do @device.network.name end %>
  </li>

  <li>
    <strong>User:</strong>
    <%= if @device.user do @device.user.name end %>
  </li>

</ul>

<span><%= link "Edit", to: device_path(@conn, :edit, @device), class: "btn btn-primary" %></span>
<span><%= link "Back", to: device_path(@conn, :index), class: "btn btn-default" %></span>